package zjut.salu.share.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import zjut.salu.share.model.IndexBannerBean;

import zjut.salu.share.greendao.IndexBannerBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig indexBannerBeanDaoConfig;

    private final IndexBannerBeanDao indexBannerBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        indexBannerBeanDaoConfig = daoConfigMap.get(IndexBannerBeanDao.class).clone();
        indexBannerBeanDaoConfig.initIdentityScope(type);

        indexBannerBeanDao = new IndexBannerBeanDao(indexBannerBeanDaoConfig, this);

        registerDao(IndexBannerBean.class, indexBannerBeanDao);
    }
    
    public void clear() {
        indexBannerBeanDaoConfig.clearIdentityScope();
    }

    public IndexBannerBeanDao getIndexBannerBeanDao() {
        return indexBannerBeanDao;
    }

}
