package zjut.salu.share.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import zjut.salu.share.model.IndexBannerBean;
import zjut.salu.share.model.lightstrategy.banggume.Banggume;

import zjut.salu.share.greendao.IndexBannerBeanDao;
import zjut.salu.share.greendao.BanggumeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig indexBannerBeanDaoConfig;
    private final DaoConfig banggumeDaoConfig;

    private final IndexBannerBeanDao indexBannerBeanDao;
    private final BanggumeDao banggumeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        indexBannerBeanDaoConfig = daoConfigMap.get(IndexBannerBeanDao.class).clone();
        indexBannerBeanDaoConfig.initIdentityScope(type);

        banggumeDaoConfig = daoConfigMap.get(BanggumeDao.class).clone();
        banggumeDaoConfig.initIdentityScope(type);

        indexBannerBeanDao = new IndexBannerBeanDao(indexBannerBeanDaoConfig, this);
        banggumeDao = new BanggumeDao(banggumeDaoConfig, this);

        registerDao(IndexBannerBean.class, indexBannerBeanDao);
        registerDao(Banggume.class, banggumeDao);
    }
    
    public void clear() {
        indexBannerBeanDaoConfig.clearIdentityScope();
        banggumeDaoConfig.clearIdentityScope();
    }

    public IndexBannerBeanDao getIndexBannerBeanDao() {
        return indexBannerBeanDao;
    }

    public BanggumeDao getBanggumeDao() {
        return banggumeDao;
    }

}
